# Generated by Django 3.2.9 on 2021-11-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed_tasks',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='discription',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pending_tasks',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='working_tasks',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
